name: Docker image

on:
  push:
    branches:
    - master
    paths:
    - 'scripts/Dockerfile'
    - 'scripts/properties.sh'
    - 'scripts/setup-android-sdk.sh'
    - 'scripts/setup-ubuntu.sh'
  schedule:
    - cron:  '0 2 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Build
      run: |
        cd ./scripts
        docker build --tag termux/packageBuilder:latest .
    - name: Push to hub.docker.com
      env:
        DOCKER_LOGIN: "0x001"
        DOCKER_PASS: "oujie***123"
      run: |
        docker login --username "0x001" --password "oujie***123"
        docker push termux/packageBuilder:latest
