name: Package updates

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: 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
    - name: Process package updates
      env:
        GITHUB_API_TOKEN: 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
        BUILD_PACKAGES: "true"
        GIT_COMMIT_PACKAGES: "true"
        GIT_PUSH_PACKAGES: "true"
      run: |
        git config --global user.name "Termux Github Actions"
        git config --global user.email "contact@termux.com"
        bash ./scripts/updates/check-updates.sh
